User.create(username: 'Rick Hendrick', password: '9244888', team_name: "Hendrick Motorsports", manufacturer: 'Chevorlet')
User.create(username: 'Roger Penske', password: '2122122', team_name: "Penske Racing", manufacturer: 'Ford')

Racecar.create(car_name: 'Napa Auto Parts Chevorlet', driver: 'Chase Elliott', number: '9', driver_bio: 'I drive the 9 car for Rick Hendrick', user_id: '1')
Racecar.create(car_name: 'Axalta Chevorlet', driver: 'William Byron', number: '24', driver_bio: 'I drive the 24 car for Rick Hendrick', user_id: '1')
Racecar.create(car_name: 'Ally Chevorlet', driver: 'Jimmie Johnson', number: '48', driver_bio: 'I drive the 48 car for Rick Hendrick', user_id: '1')
Racecar.create(car_name: 'Nationwide Chevorlet', driver: 'Alex Bowman', number: '88', driver_bio: 'I drive the 88 car for Rick Hendrick', user_id: '1')
Racecar.create(car_name: 'Discount Tire Ford', driver: 'Brad Keselowksi', number: '2', driver_bio: 'I drive the 2 for Roger Penske', user_id: '2')
Racecar.create(car_name: 'Menards Ford', driver: 'Ryan Blaney', number: '12', driver_bio: 'I drive the 12 for Roger Penske', user_id: '2')
Racecar.create(car_name: 'Hunt Brother\'s Ford', driver: 'Matt DiBenedetto', number: '21', driver_bio: 'I drive the 21 for Roger Penske', user_id: '2')
Racecar.create(car_name: 'Shell Penzoil Ford', driver: 'Joey Logano', number: '22', driver_bio: 'I drive the 22 for Roger Penske', user_id: '2')